name: etl-framework
channels:
  - pantheon
dependencies:
  - MySQL-python==1.2.3
  - psycopg2==2.6.2
  - python-dateutil==2.4.2
  - pytz==2015.2
  - six==1.9.0
  - mock==2.0.0
  - pip:
    - pylint==1.5.0
